### ISSUE TITLE
Visualizing sample data

### ISSUE THREAD

**Issue by helmifraser** [magicleap/Atlas#10]
Apologies if this is has an obvious answer. I've successfully ran the inference script on the sample scene but I'm struggling to open the .ply file. Opening in ctmviewer throws an error saying the .ply file is invalid. How do I visualize the result?

**Comment by tarrencev** [comment]
you can try use meshlab https://www.meshlab.net/

**Comment by helmifraser** [comment]
Thanks for the suggestion. Meshlab also throws an error, "Bad type name". I've tried it with the AppImage version of Meshlab as well as the one in the Ubuntu repos, and both can load sample .ply files from the Meshlab site without issue. I also get this issue whether the .ply file comes from the Colab notebook or from a local Docker container on my machine.

**Comment by Yajiang** [comment]
@helmifraser 
hi, I had the same problem with you. I solved it by add those lines in the inference code. Hope it helps.
![Screenshot from 2020-09-08 09-25-04](https://user-images.githubusercontent.com/14039036/92423879-3fcd1180-f1b5-11ea-9cf2-c5c639b895bc.png)

**Comment by helmifraser** [comment]
Hi @Yajiang, can you attach your modified inference script? Am I right in thinking you added this to tsdf.py instead of inference.py?

**Comment by Yajiang** [comment]
sorry, i made a mistake. you're right, I didn't modify the inference script. Those lines were added in "tsdf.py" file. And the problem was caused by type "int64" which was not supported by the meshlab I'm using now

**Comment by helmifraser** [comment]
Yeah, I think that's the same issue I had. Thanks for sharing!
