### ISSUE TITLE
About num of epochs

### ISSUE THREAD

**Issue by rxqy** [magicleap/Atlas#12]
Hi, thanks for sharing the code.
What's the number of epochs required to reproduce the results in the paper?

**Comment by fuy34** [comment]
Same question. I cannot find the exact number in the paper as well. 

I am very unfamiliar with pytorch-lightening. It seems the default training epoch (```max_epochs```) is 1000. Are we supposed to train it 1000 epochs? 

BTW, I download ScanNet incrementally and does not organize in its default way. May I ask if the function ```label_scene``` is used during the data preparation? https://github.com/magicleap/Atlas/blob/bee3ddbdb0935cf9aa9fc810e829115c6ab74dc5/prepare_data.py#L258

**Comment by rxqy** [comment]
Hi @fuy34 , By default it's used in the data preparation.
I think you'll need it if you want to train the semantic head.

**Comment by fuy34** [comment]
> Hi @fuy34 , By default it's used in the data preparation.
> I think you'll need it if you want to train the semantic head.

Thank you @rxqy !

**Comment by zmurez** [comment]
Re number of epics:
We manually stop training well before 1000 epochs. The best model is chosen using the validation error (usually after 100-200 epochs).

**Comment by rxqy** [comment]
Many thanks!
