### ISSUE TITLE
Question about evaluation

### ISSUE THREAD

**Issue by ymingxie** [magicleap/Atlas#19]
Thanks for your nice work!   
I have a question about dist1:  
https://github.com/magicleap/Atlas/blob/master/atlas/evaluation.py#L102
dist1 should be for each vertex in verts_trgt finding the nearest vertex in verts_pred. But why dist1 is used to compute precision instead of recall?

**Comment by zmurez** [comment]
Thank you for pointing this out. You are correct that this is a typo (I have submitted a pull request #23). It also means that the column titles in Table 3 in the paper are reversed (I updated the paper on arxiv and it should be live in about a day). This makes the metrics reflect the qualitative evaluation better (all methods do a decent job predicting vertices near the true surface, but they also predict a lot of vertices away from the true surface).
