### ISSUE TITLE
How do you generate the intrinsics.txt and pose information

### ISSUE THREAD

**Issue by foocross** [magicleap/Atlas#2]
I'm having trouble understanding how to generate the intrinsics and pose information for a new dataset. Any information would be appreciated.

**Comment by zmurez-ml** [comment]
The intrinsics and pose must be solved for using another method. COLMAP can be used for this, but you will need resolve the scale and orientation ambiguity before you can apply Atlas. Another option is to record the video with a device that can also give you the pose (for example, ARKit/ARCore can be used to create a camera app that also saves the pose).

Unfortunately I do not have any suggestions for an out of the box package that you can just run on a video and get pose (with the scale and orientation ambiguities resolved).

**Comment by Maverick054** [comment]
@zmurez-ml could you please elaborate on the values present in the pose.txt file and how can COLMAP be used for the same?
