### ISSUE TITLE
Question for results

### ISSUE THREAD

**Issue by LifeBeyondExpectations** [magicleap/Atlas#20]
Thank for releasing the code implementation.

I have a question for the results.

Is it the same pretrained weights that you reported in your paper??
Currently, I cannot obtain identical results as listed in the paper, though I used the pretrained weights from your download link.

In the paper, 
| AbsRel | AbsDiff | SqRel | RMSE |   r1    |    r2    |   r3    |
| 0.061   | 0.120    | 0.42    | 0.248 | 0.940 | 0.972 | 0.985 | 

the results I got,
| AbsRel | AbsDiff | SqRel | RMSE |   r1    |    r2    |   r3    |
| 0.117   | 0.213    | 0.092  | 0.355 | 0.852 | 0.926 | 0.963 |

**Comment by LifeBeyondExpectations** [comment]
My mistake. Thanks.

**Comment by zmurez** [comment]
Sorry for the delay. The model released is not identical to the one that was evaluated in the paper but is very similar (it was re-trained with the final version of the code once all refactoring for release was done). Does your follow up comment mean you found the issue? Is it a gotcha that is worth sharing with others here? (My first guess would be if you evaluated on a GPU with less memory and reduced `voxel_dim` then part of the scene would be outside the reconstruction volume and clipped leading to large errors in these regions.)
