### ISSUE TITLE
How to get tsdf value of scannet dataset

### ISSUE THREAD

**Issue by qiaogh97** [magicleap/Atlas#32]
Hi, I see [this code ](https://github.com/magicleap/Atlas/blob/bee3ddbdb0935cf9aa9fc810e829115c6ab74dc5/atlas/tsdf.py#L119) about loading .npz file of tsdf value. But I don't know how to get this .npz file. Can you tell me more details about this files?

**Comment by fuy34** [comment]
This npz is generated by prepare_data.py

**Comment by qiaogh97** [comment]
Thank you, I didn't notice that before.
