### ISSUE TITLE
ERROR： FileNotFoundError: [Errno 2] No such file or directory: 'DATAROOT/scannet/scannetv2_train.txt'

### ISSUE THREAD

**Issue by borishanzju** [magicleap/Atlas#6]
I have downloaded the scannet dataset and imported it into the scannet folder, but there is no train.txt file in the downloaded dataset.

**Comment by zmurez-ml** [comment]
You also need to download the train/val/test splits and the label mapping from https://github.com/ScanNet/ScanNet (Benchmark Tasks). I have updated the readme to include this. Thank you for pointing this out.
